name: Install on Windows

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: windows-latest

    strategy:
      matrix:
        shell:
          - pwsh
        script:
          - install.ps1
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Install shell
        run: sudo apt-get install -y ${{ matrix.shell }}
        if: ${{ matrix.shell != 'sh' }}
      - name: Run installation script
        run: ${{ matrix.shell }} ${{ matrix.script }}
        shell: ${{ matrix.shell }} {0}
